let g:floaterm_width = 0.8
let g:floaterm_height = 0.8
nnoremap  <silent>  <C-Space>  :FloatermToggle<CR>
tnoremap  <silent>  <C-Space>  <C-\><C-n>:FloatermToggle<CR>
"nnoremap  <silent>  <C-u>   :FloatermNext<CR>
"tnoremap  <silent>  <C-u>  <C-\><C-n>:FloatermNext<CR>
"nnoremap  <silent>  <C-y>  :FloatermNew<CR>
"tnoremap  <silent>  <C-y>  <C-\><C-n>:FloatermNew<CR>
"nnoremap  <silent>  <C-j>  :FloatermPrev<CR>
"tnoremap  <silent>  <C-j>  <C-\><C-n>:FloatermPrev<CR>